### PR TITLE
Added DS Log Level

### PR DESCRIPTION
**Pull request by c0d3rman**

### CODE REVIEW

**Comment by ajnadel** [comment]
@c0d3rman check comments

**Comment by c0d3rman** [comment]
@ajnadel Fixed

**Comment by ajnadel** [comment]
+1

**Comment by carturn** [comment]
No. The setDefaultDSLevel only sets the default, it does not allow us to actually change the driver station print level.
So the driver station will only ever log warn and higher.

**Comment by c0d3rman** [comment]
Fixed for realzies this time

**Comment by carturn** [comment]
+1, although still needs to be tested on 1/27.

**Comment by carturn** [comment]
Tested on 1/28. Does not break things.

**Pull request merged**
